In [38]:
import numpy as np
import torch as t
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [60]:
x = torch.tensor([1, 2, 3])

In [61]:
x.repeat(4, 2, 1)

tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]])

In [64]:
x.repeat(4, 2,1).size()

torch.Size([4, 2, 3])

In [39]:
pos_eeg_signal= np.arange(1, 10)

In [40]:
pos_eeg_signal

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
padded_eeg = np.pad(pos_eeg_signal, (0, 5), mode='constant', constant_values=0)

In [47]:
padded_eeg

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0])

In [45]:
pos = t.LongTensor(padded_eeg)

In [46]:
pos

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0])

In [48]:
c_mask = pos.ne(0).type(t.float)

In [49]:
c_mask

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

In [55]:
mask = pos.eq(0).unsqueeze(1).repeat(1, input_1d.size(1), 1)

In [56]:
mask

tensor([[[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [

In [54]:
input_1d.size(1)

10

In [34]:
input_1d = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = torch.float)

In [51]:
input_1d = torch.tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], dtype = torch.float)

In [37]:
input_1d.shape

torch.Size([8, 10])

In [31]:
input_1d = input_1d.unsqueeze(1)
input_1d.shape

torch.Size([10, 1])

In [22]:
input_1d

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]])

In [26]:
cnn1d_1 = nn.Conv1d(in_channels=8, out_channels=5, kernel_size=3, stride=1)
print("cnn1d_1: \n")
print(cnn1d_1(input_1d).shape, "\n")
print(cnn1d_1(input_1d))

cnn1d_1: 

torch.Size([1, 5, 8]) 

tensor([[[  0.9763,   1.3095,   1.6427,   1.9759,   2.3092,   2.6424,   2.9756,
            3.3089],
         [ -1.9052,  -2.8829,  -3.8605,  -4.8382,  -5.8158,  -6.7934,  -7.7711,
           -8.7487],
         [ -2.6257,  -3.6805,  -4.7354,  -5.7902,  -6.8451,  -7.8999,  -8.9548,
          -10.0096],
         [  0.4231,   0.5153,   0.6075,   0.6997,   0.7919,   0.8841,   0.9763,
            1.0685],
         [ -2.1019,  -2.6746,  -3.2473,  -3.8200,  -4.3927,  -4.9655,  -5.5382,
           -6.1109]]], grad_fn=<SqueezeBackward1>)


In [27]:
embed = nn.Embedding(25, 156, padding_idx=0)

In [28]:
embed(input_1d)

RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.FloatTensor instead (while checking arguments for embedding)

In [1]:
import hyperparams as hp
import pandas as pd
from torch.utils.data import Dataset, DataLoader
import os
import librosa
import numpy as np
from text import text_to_sequence
import collections
from scipy import signal
import torch as t
import math
from utils import stim_event_dict

from tqdm import tqdm

In [2]:
class OpenMIIRDataset_(Dataset):
    """Process the prepared OpenMIIR dataset."""

    def __init__(self, loaded_npz, root_dir):
        """
        Args:
            npz_file (string): Path to the .npz file with saved eeg signal data.
            root_dir (string): Directory with all the wavs.
        """
#         self.loaded_arrays = np.nditer(np.load(npz_file))
        self.loaded_arrays = loaded_npz
        self.array_indexes = self.loaded_arrays.files
        self.root_dir = root_dir

    def load_wav(self, filename):
        return librosa.load(filename, sr=hp.sample_rate)

    def __len__(self):
        return len(self.array_indexes)

    def get_wav_path(self, array_index):
        exp_id = array_index.split('_')[0]
        print('here?')
        stimulus_id = get_stimulus_id(int(exp_id))
        wav_filename = stim_event_dict[stimulus_id]
        wav_filepath = os.path.join(self.root_dir, wav_filename)
        return wav_filepath
        
    def __getitem__(self, idx):
        print('class mein')
        wav_name = self.get_wav_path(self.array_indexes[idx])
        print('wav_name', wav_name)
        eeg_array = self.loaded_arrays[self.array_indexes[idx]]

        mel = np.load(wav_name[:-4] + '.pt.npy')
        mel_input = np.concatenate([np.zeros([1, hp.num_mels], np.float32), mel[:-1,:]], axis=0)
        eeg_signal_dimensions = eeg_array.shape
        eeg_signal_length = eeg_array.shape[1]
        # text_length = len(text)
        pos_eeg_signal= np.arange(1, eeg_signal_length + 1)
        pos_mel = np.arange(1, mel.shape[0] + 1)

        sample = {
            'eeg_array': eeg_array, 
            'mel': mel, 
            'mel_input':mel_input, 
            'pos_mel': pos_mel, 
            'pos_eeg_signal': pos_eeg_signal,
            'eeg_signal_dimensions': eeg_signal_dimensions, 
            'eeg_signal_length': eeg_signal_length
        }

        return sample

In [3]:
data_path = '/home/archeron/dev/data/eeg_to_music_data'
npz_filename = 'P01_extracted.npz'

In [13]:
def get_dataset_():
    print('at get_dataset()')
    loaded_npz = np.load(os.path.join(data_path, npz_filename))
    print(loaded_npz.files[0])
    # return LJDatasets(os.path.join(hp.data_path,'metadata.csv'), os.path.join(hp.data_path,'wavs'))
    return OpenMIIRDataset_(loaded_npz, os.path.join(data_path, 'processed_wavs'))


In [38]:
def collate_fn_transformer_(batch):

    # Puts each data field into a tensor with outer dimension batch size
    if isinstance(batch[0], collections.Mapping):

        eeg_array = [d['eeg_array'] for d in batch]
        mel = [d['mel'] for d in batch]
        mel_input = [d['mel_input'] for d in batch]
        pos_mel = [d['pos_mel'] for d in batch]
        pos_eeg_signal= [d['pos_eeg_signal'] for d in batch]
        eeg_signal_length = [d['eeg_signal_length'] for d in batch]
        
        eeg_array = [i for i,_ in sorted(zip(eeg_array, eeg_signal_length), key=lambda x: x[1], reverse=True)]
        mel = [i for i, _ in sorted(zip(mel, eeg_signal_length), key=lambda x: x[1], reverse=True)]
        mel_input = [i for i, _ in sorted(zip(mel_input, eeg_signal_length), key=lambda x: x[1], reverse=True)]
        pos_eeg_signal = [i for i, _ in sorted(zip(pos_eeg_signal, eeg_signal_length), key=lambda x: x[1], reverse=True)]
        pos_mel = [i for i, _ in sorted(zip(pos_mel, eeg_signal_length), key=lambda x: x[1], reverse=True)]
        eeg_signal_length = sorted(eeg_signal_length, reverse=True)
        # PAD sequences with largest length of the batch
        eeg_array = _prepare_eeg_data(eeg_array)
        mel = _pad_mel(mel)
        mel_input = _pad_mel(mel_input)
        pos_mel = _prepare_data(pos_mel).astype(np.int32)
        pos_eeg_signal = _prepare_data(pos_eeg_signal).astype(np.int32)


        return t.FloatTensor(eeg_array), t.FloatTensor(mel), t.FloatTensor(mel_input), t.LongTensor(pos_eeg_signal), t.LongTensor(pos_mel), t.LongTensor(eeg_signal_length)

    raise TypeError(("batch must contain tensors, numbers, dicts or lists; found {}"
                     .format(type(batch[0]))))

In [6]:
def get_stimulus_id(event_id):
    if event_id < 1000:
        return int(event_id / 10)
    else:
        return event_id

In [19]:
def _pad_eeg_data(input_array, length):
    print('input_array shape: ', input_array.shape[1])
    _pad = 0
    return np.stack([np.pad(x, (0, length - input_array.shape[1]), mode='constant', constant_values=_pad) for x in input_array])

def _pad_data(x, length):
    _pad = 0
    return np.pad(x, (0, length - x.shape[0]), mode='constant', constant_values=_pad)

def _prepare_eeg_data(inputs):
    max_len = max((x.shape[1] for x in inputs))
    print('at _prepare_eeg_data()')
    print('max length: ', max_len)
    return np.stack([_pad_eeg_data(x, max_len) for x in inputs])

def _prepare_data(inputs):
    max_len = max((len(x) for x in inputs))
    return np.stack([_pad_data(x, max_len) for x in inputs])

def _pad_per_step(inputs):
    timesteps = inputs.shape[-1]
    return np.pad(inputs, [[0,0],[0,0],[0, hp.outputs_per_step - (timesteps % hp.outputs_per_step)]], mode='constant', constant_values=0.0)

def get_param_size(model):
    params = 0
    for p in model.parameters():
        tmp = 1
        for x in p.size():
            tmp *= x
        params += tmp
    return params

def get_dataset():
    print('at get_dataset()')
    # return LJDatasets(os.path.join(hp.data_path,'metadata.csv'), os.path.join(hp.data_path,'wavs'))
    return OpenMIIRDataset(os.path.join(hp.data_path, hp.npz_filename), os.path.join(hp.data_path, 'processed_wavs'))

def get_post_dataset():
    return PostDatasets(os.path.join(hp.data_path,'metadata.csv'), os.path.join(hp.data_path,'wavs'))

def _pad_mel(inputs):
    _pad = 0
    def _pad_one(x, max_len):
        mel_len = x.shape[0]
        return np.pad(x, [[0,max_len - mel_len],[0,0]], mode='constant', constant_values=_pad)
    max_len = max((x.shape[0] for x in inputs))
    return np.stack([_pad_one(x, max_len) for x in inputs])

def get_stimulus_id(event_id):
    if event_id < 1000:
        return int(event_id / 10)
    else:
        return event_id


In [39]:
dataset = get_dataset_()

at get_dataset()
121_520_8140_P01


In [43]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True, collate_fn=collate_fn_transformer_, drop_last=True, num_workers=1)

In [44]:
eeg_array, mel, mel_input, pos_eeg_signal, pos_mel, _ = next(iter(dataloader))

class mein
here?
wav_name /home/archeron/dev/data/eeg_to_music_data/processed_wavs/S11_Chim_Chim_Cheree_no_lyrics_processed.wav
class mein
here?
wav_name /home/archeron/dev/data/eeg_to_music_data/processed_wavs/S11_Chim_Chim_Cheree_no_lyrics_processed.wav
class mein
here?
wav_name /home/archeron/dev/data/eeg_to_music_data/processed_wavs/S12_Take_Me_Out_To_The_Ballgame_no_lyrics_processed.wav
class mein
here?
wav_name /home/archeron/dev/data/eeg_to_music_data/processed_wavs/S11_Chim_Chim_Cheree_no_lyrics_processed.wav
at _prepare_eeg_data()
max length:  10789
input_array shape:  10789
input_array shape:  10787
input_array shape:  7983
input_array shape:  7616
class mein
here?
wav_name /home/archeron/dev/data/eeg_to_music_data/processed_wavs/S23_Star_Wars_Theme_processed.wav
class mein
here?
wav_name /home/archeron/dev/data/eeg_to_music_data/processed_wavs/S03_Jingle_Bells_lyrics_processed.wav
class mein
here?
wav_name /home/archeron/dev/data/eeg_to_music_data/processed_wavs/S04_Mary_Had

In [45]:
eeg_array

tensor([[[-2.0865e-03, -2.0887e-03, -2.0854e-03,  ..., -2.1194e-03,
          -2.1182e-03, -2.1220e-03],
         [-1.3048e-03, -1.3110e-03, -1.3085e-03,  ..., -1.3301e-03,
          -1.3292e-03, -1.3355e-03],
         [ 8.7062e-03,  8.7016e-03,  8.7020e-03,  ...,  8.6221e-03,
           8.6237e-03,  8.6199e-03],
         ...,
         [-1.2700e-02, -1.2702e-02, -1.2703e-02,  ..., -1.2701e-02,
          -1.2700e-02, -1.2700e-02],
         [-5.8073e-03, -5.8065e-03, -5.8051e-03,  ..., -5.8142e-03,
          -5.8136e-03, -5.8130e-03],
         [ 0.0000e+00,  1.0000e+03,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00]],

        [[-6.3731e-04, -6.4203e-04, -6.4909e-04,  ..., -7.2584e-04,
           0.0000e+00,  0.0000e+00],
         [-1.1725e-03, -1.1745e-03, -1.1830e-03,  ..., -1.2736e-03,
           0.0000e+00,  0.0000e+00],
         [ 7.8067e-03,  7.8036e-03,  7.7974e-03,  ...,  7.6998e-03,
           0.0000e+00,  0.0000e+00],
         ...,
         [-1.0519e-02, -1

In [46]:
eeg_array.shape

torch.Size([4, 69, 10789])

In [47]:
eeg_array[0]

tensor([[-2.0865e-03, -2.0887e-03, -2.0854e-03,  ..., -2.1194e-03,
         -2.1182e-03, -2.1220e-03],
        [-1.3048e-03, -1.3110e-03, -1.3085e-03,  ..., -1.3301e-03,
         -1.3292e-03, -1.3355e-03],
        [ 8.7062e-03,  8.7016e-03,  8.7020e-03,  ...,  8.6221e-03,
          8.6237e-03,  8.6199e-03],
        ...,
        [-1.2700e-02, -1.2702e-02, -1.2703e-02,  ..., -1.2701e-02,
         -1.2700e-02, -1.2700e-02],
        [-5.8073e-03, -5.8065e-03, -5.8051e-03,  ..., -5.8142e-03,
         -5.8136e-03, -5.8130e-03],
        [ 0.0000e+00,  1.0000e+03,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])

In [ ]:
mel

In [ ]:
pbar = tqdm(dataloader)
print('ummm')
for i, data in enumerate(pbar):
    print(i)
    print('hulloooooo')
    eeg_array, mel, mel_input, pos_eeg_signal, pos_mel, _ = data
    

In [ ]:
from train_transformer import main

In [ ]:
main()


^^ running succesfully at default settings. no checkpoints (<= fix later)

MAIN: shove in eeg data and train and generate sample

exp #1: add raw numpy array 

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8]])

In [ ]:
a.shape[1]

In [ ]:
x = np.arange(20)

In [ ]:
x[::2] 

In [ ]:
x[0::2]

In [ ]:
x[1::2]